<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hotel.Domain\Hotel.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DTOs\" />
    <Folder Include="Interface\" />
    <Folder Include="Mappings\" />
    <Folder Include="Service\" />
    <Folder Include="Response\" />
  </ItemGroup>

</Project>
